//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public long Id { get; set; }
        public System.DateTimeOffset ActiveFrom { get; set; }
        public System.DateTimeOffset ActiveUntil { get; set; }
        public string Text { get; set; }
    }
}
