//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardRecipient
    {
        public long Id { get; set; }
        public long Person { get; set; }
        public long Award { get; set; }
        public System.DateTimeOffset DateAwarded { get; set; }
    
        public virtual Award Award1 { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
