//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class Due
    {
        public long Id { get; set; }
        public long Member { get; set; }
        public decimal Amount { get; set; }
        public System.DateTimeOffset DatePaid { get; set; }
        public System.DateTimeOffset PaidThroughDate { get; set; }
        public long PaymentType { get; set; }
        public string Notes { get; set; }
    
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual Person Person { get; set; }
    }
}
