//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Speeches = new HashSet<Speech>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long Manual { get; set; }
        public int ProjectNumber { get; set; }
        public int TargetTimeLowerBoundInSeconds { get; set; }
        public int TargetTimeUpperBoundInSeconds { get; set; }
        public string Notes { get; set; }
    
        public virtual Manual Manual1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speech> Speeches { get; set; }
    }
}
