//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speech()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long Project { get; set; }
        public long Speaker { get; set; }
        public int TimeInSeconds { get; set; }
        public long Meeting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Meeting Meeting1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Project Project1 { get; set; }
    }
}
