//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTopic
    {
        public long Id { get; set; }
        public string Question { get; set; }
        public long Meeting { get; set; }
        public long Speaker { get; set; }
        public int TimeInSeconds { get; set; }
    
        public virtual Meeting Meeting1 { get; set; }
        public virtual Person Person { get; set; }
    }
}
