//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasePlayground
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class ToastmastersStagingConnection : DbContext
    {
        public ToastmastersStagingConnection()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            return string.Format(ConfigurationManager.ConnectionStrings["ToastmastersStagingConnection"].ConnectionString, Environment.GetEnvironmentVariable("ToastmastersDatabasePassword"));
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<AwardRecipient> AwardRecipients { get; set; }
        public virtual DbSet<AwardType> AwardTypes { get; set; }
        public virtual DbSet<Due> Dues { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<GrammarianReport> GrammarianReports { get; set; }
        public virtual DbSet<GrammarianReportLine> GrammarianReportLines { get; set; }
        public virtual DbSet<Manual> Manuals { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MeetingAward> MeetingAwards { get; set; }
        public virtual DbSet<MeetingAwardType> MeetingAwardTypes { get; set; }
        public virtual DbSet<MeetingParticipant> MeetingParticipants { get; set; }
        public virtual DbSet<MemberStatu> MemberStatus { get; set; }
        public virtual DbSet<OfficerRole> OfficerRoles { get; set; }
        public virtual DbSet<OfficerService> OfficerServices { get; set; }
        public virtual DbSet<ParticipantRole> ParticipantRoles { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Speech> Speeches { get; set; }
        public virtual DbSet<TableTopic> TableTopics { get; set; }
    }
}
